version: '3.7'

services:
  postgres:
    image: 'postgres:9.5.14'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - bwm-postgres:/var/lib/postgresql/data

  redis:
    image: 'redis:6.2.4'
    ports:
      - '6379:6379'
    volumes:
      - bwm-redis:/var/lib/redis/data

  app:
    build:
      context: .
      args:
        PUMA_PORT: ${PUMA_PORT}
    depends_on:
      - 'postgres'
      - 'sidekiq'
    volumes:
      - .:/var/www/barcode_workflow_manager
    ports:
      - ${PUMA_PORT}:${PUMA_PORT}
    env_file:
      - .env

  sidekiq:
    build:
      context: .
      args:
        PUMA_PORT: ${PUMA_PORT}
    command: bundle exec sidekiq
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/var/www/barcode_workflow_manager
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: web.Dockerfile
      args:
        PROJECT_DOMAIN: ${PROJECT_DOMAIN}
        PORT: ${PORT}
        PUMA_PORT: ${PUMA_PORT}
    depends_on:
      - app
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}

  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"

volumes:
  bwm-redis:
  bwm-postgres:
