FROM nginx:latest

RUN apt-get update -qq && apt-get -y install apache2-utils

ENV RAILS_ROOT /var/www/barcode_workflow_manager
ARG PROJECT_DOMAIN

WORKDIR $RAILS_ROOT

RUN mkdir log

COPY public public/
COPY nginx.conf /tmp/nginx.conf
RUN envsubst '${RAILS_ROOT} ${PROJECT_DOMAIN}' < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]
