version: '3.7'

services:
  postgres:
    image: 'postgres:9.5.14'
    environment:
      POSTGRES_USER: barcode_workflow_manager
      POSTGRES_PASSWORD: mypassword
    ports:
      - '5432:5432'
    volumes:
      - bwm-postgres:/var/lib/postgresql/data

  redis:
    image: 'redis:3.2.9'
    ports:
      - '6379:6379'
    volumes:
      - bwm-redis:/var/lib/redis/data

  app:
    build:
      context: .
    depends_on:
      - 'postgres'
      - 'sidekiq'
    volumes:
      - .:/var/www/barcode_workflow_manager
    ports:
      - "3000:3000"
    env_file:
      - .env

  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/var/www/barcode_workflow_manager
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
      args:
        PROJECT_DOMAIN: ${PROJECT_DOMAIN}
    depends_on:
      - app
    env_file:
      - .env
    ports:
      - '80:80'

volumes:
  bwm-redis:
  bwm-postgres:
