services:
  nginx:
    build:
      context: .
    dockerfile: web_ssl.Dockerfile
    args:
      PROJECT_DOMAIN: ${PROJECT_DOMAIN}
      PORT: ${PORT}
      PUMA_PORT: ${PUMA_PORT}
    depends_on:
      - app
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
