version: '3'

volumes:
  views:
  image_assets:
  redis:
  postgres:

services:
  postgres:
    image: 'postgres:9.5.14'
    environment:
      POSTGRES_USER: gbol5
      POSTGRES_PASSWORD: passwordpsql
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - '.env'

  redis:
    image: 'redis:3.2.9'
    command: redis-server
    volumes:
      - 'redis:/data'

  app:
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    image: gbol5/barcode_workflow_manager:app
#    build:
#      context: .
#      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/var/www/barcode_workflow_manager
      - views:/var/www/barcode_workflow_manager/app/views/home
      - image_assets:/var/www/barcode_workflow_manager/app/assets/images/project_images
    ports:
      - "3000:3000"
    env_file:
      - '.env'
    depends_on:
      - 'postgres'
      - 'sidekiq'

  sidekiq:
    image: gbol5/barcode_workflow_manager:sidekiq
#    build:
#      context: .
#      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - 'redis'
    command: sidekiq -C config/sidekiq.yml
    volumes:
      - '.:/var/www/barcode_workflow_manager'
    env_file:
      - '.env'

  web:
    image: gbol5/barcode_workflow_manager:web
#    build:
#      context: .
#      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - 'app'
    ports:
      - 80:80
