version: '3'
services:
  postgres:
    image: 'postgres:9.5.14'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - '.env'

  redis:
    image: 'redis:3.2.9'
    command: redis-server
    volumes:
      - 'redis:/data'

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/gbol5
    ports:
      - "3000:3000"
    env_file:
      - '.env'
    depends_on:
      - 'postgres'
      - 'redis'

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: sidekiq -C config/sidekiq.yml
    volumes:
      - '.:/gbol5'
    env_file:
      - '.env'

volumes:
  redis:
  postgres: