version: '3'
services:
  postgres:
    image: 'postgres:9.5.14'
    environment:
      POSTGRES_USER: gbol5
      POSTGRES_PASSWORD: passwordpsql
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - '.env'

  redis:
    image: 'redis:3.2.9'
    command: redis-server
    volumes:
      - 'redis:/data'

  web:
    image: 'gbol5/bartender:latest'
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/bartender
      - /data1/sciebo/PhD/GBOL/WebApp/Docker/gbol5_config/.env:/bartender/.env
      - /data1/sciebo/PhD/GBOL/WebApp/Docker/gbol5_config/application.yml:/bartender/config/application.yml
      - /data1/sciebo/PhD/GBOL/WebApp/Docker/gbol5_config/project_images:/bartender/app/assets/images/project_images
      - /data1/sciebo/PhD/GBOL/WebApp/Docker/gbol5_config/about.html.erb:/bartender/app/views/home/about.html.erb
      - /data1/sciebo/PhD/GBOL/WebApp/Docker/gbol5_config/impressum.html.erb:/bartender/app/views/home/impressum.html.erb
      - /data1/sciebo/PhD/GBOL/WebApp/Docker/gbol5_config/privacy_policy.html.erb:/bartender/app/views/home/privacy_policy.html.erb
    ports:
      - "3000:3000"
    env_file:
      - '.env'
    depends_on:
      - 'postgres'
      - 'redis'

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: sidekiq -C config/sidekiq.yml
    volumes:
      - '.:/bartender'
    env_file:
      - '.env'

volumes:
  redis:
  postgres: