version: '3.7'

services:
  postgres:
    image: 'postgres:9.5.14'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - barkeeper-postgres:/var/lib/postgresql/data

  redis:
    image: 'redis:6.2.4'
    ports:
      - '6379:6379'
    volumes:
      - barkeeper-redis:/var/lib/redis/data

  app:
    build:
      context: .
      args:
        PUMA_PORT: ${PUMA_PORT}
    depends_on:
      - 'postgres'
      - 'sidekiq'
    volumes:
      - .:/var/www/barkeeper
    ports:
      - ${PUMA_PORT}:${PUMA_PORT}
    env_file:
      - .env

  sidekiq:
    build:
      context: .
      args:
        PUMA_PORT: ${PUMA_PORT}
    command: bundle exec sidekiq
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/var/www/barkeeper
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: web.Dockerfile
      args:
        PROJECT_DOMAIN: ${PROJECT_DOMAIN}
        PORT: ${PORT}
        PUMA_PORT: ${PUMA_PORT}
    depends_on:
      - app
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}

  mail:
    image: boky/postfix:latest
    environment:
      ALLOWED_SENDER_DOMAINS: ${PROJECT_DOMAIN}
    ports:
      - '1578:578'

volumes:
  barkeeper-redis:
  barkeeper-postgres:
