version: '3.7'

services:
  postgres:
    image: 'postgres:14.1'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - barkeeper-postgres:/var/lib/postgresql/data
    restart: always

  redis:
    image: 'redis:6.2.6'
    ports:
      - '6379:6379'
    volumes:
      - barkeeper-redis:/var/lib/redis/data
    restart: always

  app:
    image: barkeeper
    depends_on:
      - postgres
      - sidekiq
    volumes:
      - .:/var/www/barkeeper
    ports:
      - ${PUMA_PORT}:${PUMA_PORT}
    env_file:
      - .env
    restart: always

  sidekiq:
    image: barkeeper
    build:
      context: .
      args:
        PUMA_PORT: ${PUMA_PORT}
        RAILS_ENV: ${RAILS_ENV}
    command: bundle exec sidekiq
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/var/www/barkeeper
    env_file:
      - .env
    restart: always

  nginx:
    build:
      context: .
      dockerfile: web.Dockerfile
      args:
        PROJECT_DOMAIN: ${PROJECT_DOMAIN}
        PORT: ${PORT}
        SSL_PORT: ${SSL_PORT}
        PUMA_PORT: ${PUMA_PORT}
    depends_on:
      - app
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
      - ${SSL_PORT}:${SSL_PORT}
    restart: always

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  mail:
    image: boky/postfix:latest
    environment:
      ALLOWED_SENDER_DOMAINS: ${PROJECT_DOMAIN}
    ports:
      - '1578:578'
    restart: always

volumes:
  barkeeper-redis:
  barkeeper-postgres:
