default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'].gsub('?', '_development?') %>

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'].gsub('?', '_test?') %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'].gsub('?', '_production?') %>