default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  timeout: 5000

test:
  <<: *default
  database: gbol5_test
  username: <%= Rails.application.credentials.gbol5_database_user %>
  password: <%= Rails.application.credentials.gbol5_dev_db_password %>

development:
  <<: *default
  database: gbol5_development
  username: <%= Rails.application.credentials.gbol5_database_user %>
  password: <%= Rails.application.credentials.gbol5_dev_db_password %>

production:
  <<: *default
  database: gbol_production
  username: <%= Rails.application.credentials.gbol5_database_user %>
  password: <%= Rails.application.credentials.gbol5_database_password %>
