default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  timeout: 5000
  username: <%= Rails.application.credentials.gbol5_database_user %>
  password: <%= Rails.application.credentials.gbol5_database_password %>

development:
  <<: *default
  database: gbol5_development

test:
  <<: *default
  database: gbol5_test

production:
  <<: *default
  database: gbol5_production