# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  secret_key_base: a4f1d273939885cb0f43ce604d43a0f1f5b08595913da4ae722b575b570c57bff75dce1969dcb58a751e3b34f1b932cca1c7936da035c59fbbe33ad6174719bd

test:
  secret_key_base: 0df5a2ece17fc2830ec3902addd5410674f40848d34a7ea02fdf987818c82094c0be3e0c7d2e33e9551538e3a48d9ac56bc453fc0c8d868d96d8e85a93f2c89b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
