# Write SPECIMENS & STATUS to Excel-XML (xls) for use by ZFMK for their "Portal / db : bolgermany.de "
class XmlUploader < ApplicationRecord
  include ActionView::Helpers

  # TODO: later rename  :uploaded_file to xml_File or s.th.
  has_attached_file :uploaded_file,
                    :path => "/specimens.xls"

  # Validate content type
  validates_attachment_content_type :uploaded_file, :content_type => /\Aapplication\/xml/

  # Validate filename
  validates_attachment_file_name :uploaded_file, :matches => [/xls\Z/]

  def create_uploaded_file
    file_to_upload = File.open("specimens.xls", "w")
    file_to_upload.write(xml_string)
    file_to_upload.close

    self.uploaded_file = File.open("specimens.xls")
    self.save!
  end

  def xml_string
    # Get all markers in current project
    project_id = current_project_id
    markers = Marker.in_project(project_id)

    @states = %w(Baden-WÃ¼rttemberg Bayern Berlin Brandenburg Bremen Hamburg Hessen Mecklenburg-Vorpommern Niedersachsen Nordrhein-Westfalen Rheinland-Pfalz Saarland Sachsen Sachsen-Anhalt Schleswig-Holstein ThÃ¼ringen)

    @header_cells = ["GBOL5 specimen ID",
                     "Feldnummer",
                     "Institut",
                     "Sammlungs-Nr.",
                     "Familie",
                     "Taxon-Name",
                     "Erstbeschreiber Jahr",
                     "evtl. Bemerkung Taxonomie",
                     "Name",
                     "Datum",
                     "Gewebetyp und Menge",
                     "Anzahl Individuen",
                     "Fixierungsmethode"   ,
                     "Entwicklungsstadium",
                     "Sex",
                     "evtl. Bemerkungen zur Probe",
                     "Fundortbeschreibung",
                     "Region",
                     "Bundesland",
                     "Land",
                     "Datum",
                     "Sammelmethode",
                     "Breitengrad",
                     "LÃ¤ngengrad",
                     "Benutzte Methode",
                     "Ungenauigkeitsangabe",
                     "HÃ¶he/Tiefe [m]",
                     "Habitat",
                     "Sammler",
                     "Nummer",
                     "BehÃ¶rde"
    ]

    markers.each do |m|
      @header_cells << "#{m.name} - URL"
      @header_cells << "#{m.name} - Marker Sequence"
      @header_cells << "#{m.name} - Genbank ID"
    end

    builder = Nokogiri::XML::Builder.new do |xml|

      xml.comment("Generated by gbol5.de web app on #{Time.zone.now}")
      xml.Workbook('xmlns'=>"urn:schemas-microsoft-com:office:spreadsheet",
                   'xmlns:o'=>"urn:schemas-microsoft-com:office:office",
                   'xmlns:x'=>"urn:schemas-microsoft-com:office:excel",
                   'xmlns:ss'=>"urn:schemas-microsoft-com:office:spreadsheet",
                   'xmlns:html'=>"http://www.w3.org/TR/REC-html40") {
        xml.Worksheet('ss:Name'=>"Sheet1") {
          xml.Table {
            xml.Row {

              @header_cells.each do |o|
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text(o)
                  }
                }
              end

            }

            # get all Individuals in current project
            Individual.includes(isolates: [contigs: [:marker_sequence, :marker, :isolate]], species: :family).in_project(project_id).find_each do |individual|

              xml.Row {
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    # previous version with "Gbol-Nr.":
                    # xml.text(individual.try(:isolates).first.try(:lab_nr))
                    xml.text(individual.id)
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    if individual.collection_nr
                      if individual.collection_nr.include? 's.n.' or individual.collection_nr.include? 's. n.'
                        xml.text('')
                      else
                        xml.text(individual.collection_nr)
                      end
                    end
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text(individual.herbarium)
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    if individual.specimen_id == "<no info available in DNA Bank>"
                      xml.text('')
                    else
                      xml.text(individual.specimen_id)
                    end
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text(individual.try(:species).try(:family).try(:name))
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text(individual.try(:species).try(:name_for_display))
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text(individual.try(:species).try(:author))
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text('')
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text(individual.determination)
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text('')
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text('Blattmaterial')
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text('')
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text('Silica gel')
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text('')
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text('')
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text("gbol5.de/individuals/#{individual.id}/edit")
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text(individual.locality)
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text('')
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {

                    if individual.country == 'Germany' or individual.country == 'Deutschland'
                      # tests first if is a Bundesland; outputs nothing if other crap was entered in this field:

                      if @states.include? individual.state_province
                        xml.text(individual.state_province)
                      else
                        xml.text('')
                      end

                      # stuff from Schweiz etc
                    else
                      xml.text('Europa')
                    end
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text(individual.country)
                  }
                }

                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text(individual.collection_date)
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text('')
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text(number_with_precision(individual.latitude, precision:5))
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text(number_with_precision(individual.longitude, precision:5))
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text('')
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text('')
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text(individual.elevation)
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text(individual.habitat)
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text(individual.collector)
                  }
                }
                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text(individual.collection_nr)
                  }
                }

                xml.Cell {
                  xml.Data('ss:Type' => "String") {
                    xml.text('')
                  }
                }

                # Find longest marker sequence per GBoL marker for each individual
                longest_sequences = {}

                individual.try(:isolates).each do |iso|
                  markers.each do |current_marker|

                    current_contig = iso.try(:contigs).includes(marker_sequence: :contigs).where(:marker_id => current_marker.id).first
                    current_marker_sequence = current_contig&.marker_sequence
                    current_ms_sequence = current_marker_sequence&.sequence

                    if current_ms_sequence
                      longest_sequences[current_marker.id] ||= current_marker_sequence
                      if current_ms_sequence.length > longest_sequences[current_marker.id].sequence.length
                        longest_sequences[current_marker.id] = current_marker_sequence
                      end
                    end

                  end
                end

                markers.each do |marker|
                  current_sequence = longest_sequences[marker.id]
                  current_ms = current_sequence&.sequence

                  # URL zum contig in GBoL5 WebApp
                  xml.Cell {
                    xml.Data('ss:Type' => "String") {
                      current_contig_id = current_sequence&.contigs&.first&.id
                      if current_contig_id
                        xml.text("gbol5.de/contigs/#{current_contig_id}/edit") #edit_contig_path(current_sequence.contigs.first)
                      end
                    }
                  }

                  # Markersequenz
                  xml.Cell {
                    xml.Data('ss:Type' => "String") {
                      if current_ms
                        xml.text(current_ms)
                      end
                    }
                  }

                  # Genbank ID
                  xml.Cell {
                    xml.Data('ss:Type' => "String") {
                      if current_ms && current_sequence&.genbank
                        xml.text(current_sequence.genbank)
                      end
                    }
                  }
                end
              }
            end
          }
        }
      }
    end

    builder.to_xml
  end
end